### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [mpyw/oh-my-zsh-lukerandall-extended#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by mpyw** [comment]
https://github.com/mpyw/oh-my-zsh-lukerandall-extended/commit/e3d52af52daab7493aaa3c37b96ac56fe3271f0b resolves #2
